### ISSUE TITLE
I cant get a Minecraft project zone server to run

### ISSUE THREAD

**Issue by FSCbro** [HalbFettKaese/VanillaMiniMap#2]
Hi, everyone. I have a huge issue when I am trying to start my own project ozone 3 server. I downloaded the modpack on the curseforge downloader, ran it, then also downloaded the server project ozone pack. Then I extracted it and I try to run the start file, when doing so a prompt comes up on my cmd saying"

C:\Users\Frank\Downloads\PO3+-+3.4.11Fserver>"C:\Program Files\Java\jre1.8.0_301\bin\java.exe" -Xmx15360m -Xms256m -jar forge-1.12.2-14.23.5.2860.jar nogui

The system cannot find the path specified.

C:\Users\Frank\Downloads\PO3+-+3.4.11Fserver>pause

Press any key to continue . . .

"

How can I run the server without getting this error code. I am trying to run the server asap so if anyone can help me with this it would be amazing.

IMAGES
![Item1](https://github.com/HalbFettKaese/VanillaMiniMap/assets/108045122/bc2a5784-48da-4d79-b6b9-02affaccc5d7)

![Item2](https://github.com/HalbFettKaese/VanillaMiniMap/assets/108045122/7b6750f1-bd69-4c03-9f28-af06536fb753)

![Item3](https://github.com/HalbFettKaese/VanillaMiniMap/assets/108045122/6d880890-5ec3-4a69-93a7-db207d2db5fe)

**Comment by HalbFettKaese** [comment]
Your problem is completely unrelated to this repo, so I will close the request. 
If you need help, try using google or asking in a help forum.

That being said, the problem seems to be that you're not entering the right path to your JRE. (the very first argument that you entered in your cmd)
If you want to find what that path is, try googling "how to find JRE path" for detailed instructions.

I will not answer further prompts because this is not the platform for discussions like that, so if you do have more questions, do seek a proper help forum.
